=== DaveMacaulay/magento-wysiwyg/etc/wysiwyg.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="types">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="wysiwyg" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="label"/>
                                        <xs:element type="xs:string" name="version"/>
                                        <xs:element type="xs:string" name="component"/>
                                        <xs:element type="xs:string" name="template"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DaveMacaulay/magento-wysiwyg/etc/wysiwyg.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="wysiwyg.xsd">
    <types>
        <wysiwyg name="tinymce_v4">
            <label>TinyMCE</label>
            <version>4.6.4</version>
            <component>Magento_Wysiwyg/js/tinymcev4/wysiwyg-component</component>
            <template>Magento_Wysiwyg/tinymcev4/wysiwyg</template>
        </wysiwyg>
        <wysiwyg name="tinymce_v3">
            <label>TinyMCE</label>
            <version>3.0.0</version>
            <component>Magento_Wysiwyg/js/tinymcev3/wysiwyg-component</component>
            <template>Magento_Wysiwyg/tinymcev3/wysiwyg</template>
        </wysiwyg>
    </types>
</config>
